### ISSUE TITLE
Adding this to https://transform.now.sh/

### ISSUE THREAD

**Issue by ritz078** [brikou/CSS-in-JS-generator#1]
This looks like a really great project.

I have developed an IDE https://transform.now.sh/ and would love to have this on the site. Let me know if you can help or else, I will be happy to do it myself when I have time.

**Comment by brikou** [comment]
I know transform.now.sh and really like it! It would be great to have this tool in it! You can DM me by twitter if you want some explanation about source code...

**Comment by ritz078** [comment]
Here is an initial implementation https://transform-bhlmrjfric.now.sh/css-to-emotion . One thing that would make it a bit better would be an option to export all the functions from a single file (maybe). That would be better for an IDE.

**Comment by brikou** [comment]
Great job!

I've opened an issue in prettier to support injectGlobal template literal https://github.com/prettier/prettier/issues/2970

The best way is to avoid flattening generating js in a single file, maybe you can add a "download archive" button, what do you think ?

NB: can you also add a comment pointing to the repo?

**Comment by ritz078** [comment]
Download archive is something that can be additional feature but not a replacement. I would want the REPL output to be useful and if someone wants to download archive, he can have separate files.

I am planning to add a link to respective npm packages' GitHub page in all transformations on website and the description on the GitHub repo. I have also added you as a contributor [here](https://github.com/transform-it/transform-www).

**Comment by brikou** [comment]
I think I can do it, but this would be the only output as all exported `const` would become exported `function` to avoid cyclic problem. It would allow usage of a single `import * from "./myGeneratedEmotionFile.js"` and then have completion. I know that babel < 7.x does not mark templateLiteral as PURE function (see https://github.com/babel/babel/pull/6327) so tree shaking does not work (and this is a problem with big files).
Another good thing with function instead of const, is that emotion hydrate behaviour would work as expected (right now generated classes are not considered as critical).
This change would make the output a little scary because of a single file, but on the other side it would simplify many things. Also, I'm almost sure that prettier would not work anymore until https://github.com/prettier/prettier/pull/2961 is solved.

I'll try to update it today

**Comment by brikou** [comment]
@ritz078 You can already try with no_more_archive branch, code is much simpler as I removed a lot of code... see #4, ping me once a beta is ready
